### ISSUE TITLE
Showing Bench Players Scores

### ISSUE THREAD

**Issue by Metz83** [mikemountain/fantasy-football-scoreboard#12]
I got all my hardware in Thursday all pumped to try this out, only to see that Sleeper changed their API. Super glad you were able to get this back up and running. I just completed my scoreboard and my opponents score is showing his bench players scores as well. Is it something I did? Is it something that I just have to deal with? If so, no big deal. Just happy you were able to get this back up and running. Thanks

**Comment by mikemountain** [comment]
Great catch, thanks for this! I messed something up for sure. Will be pushing out a fix soon.

**Comment by mikemountain** [comment]
@Metz83 can you pull the master branch and give it another run?

**Comment by Metz83** [comment]
@mikemountain It works. Awesome! Thank you very much!
