### ISSUE TITLE
Scores will occasionally zero out for an update before coming back

### ISSUE THREAD

**Issue by tjhall9** [mikemountain/fantasy-football-scoreboard#25]
Every minute or two one of the scores (sometimes both) will go red and back to zero. After the next refresh I'll get the BIG PLAY animation and all the points will come back in gold.

**Comment by mikemountain** [comment]
Sleeper, ESPN, or Yahoo? Just so I can narrow it down

**Comment by mikemountain** [comment]
Wow, so just by poking around, it looks like it's a sleeper issue... Check it out: 

grab your league id, and go to the url `https://sleeper.app/roster/<league_id>/1` and swap out the 1 at the end of the url until you find your team 

this is your teams roster, and was the easiest way for the app to grab scores (it worked flawlessly last year). for some reason??? on refreshes, the scores change! it makes NO SENSE.

**Comment by mikemountain** [comment]
This is super annoying, and I'm not sure if it's Sleeper just dropping the ball (again) on a first game of the season or not, so I'll have to keep investigating and won't be able to fix this tonight.

To stop the stupid "big play" and colour changes constantly happening because of this, I just quickly pushed something that stops it for sleeper

**Comment by mikemountain** [comment]
@tjhall9 right now, I'm noticing this isn't happening today so far and it might have just been an opening night bungle by Sleeper. If you catch it happening to you again, please bump this asap!

**Comment by tjhall9** [comment]
I've noticed the same, fingers crossed it holds

**Comment by mikemountain** [comment]
I'm going to push a couple of small changes to the f/espn-and-yahoo branch, looks like sleeper fixed a URL they broke last season, which should allow me both easier and quicker checks (so I've increased the score updating to every 5 seconds)

**Comment by morpherios** [comment]
Just had a 0 update for both teams on sleeper. Then one team came back with
a big play update, then the second team

**Comment by mikemountain** [comment]
Yeah I'm noticing similar things, there are a lot of issues with Sleeper right now, in app and on web too. Lots of scores are struggling to update on time, so this is currently just Sleeper struggling with week 1 load it seems unfortunately :(

**Comment by morpherios** [comment]
I agree. Crazy back And forth scoring updates. Lagged scores, lots.

**Comment by tjhall9** [comment]
Sleeper got their act together, this weekend was perfect for scoring

**Comment by morpherios** [comment]
Negative. Happened to me at least 2 times that I noticed in the Early set
of games. Didn't have it running for the later set.
