### ISSUE TITLE
module not found error: Yahoo_oauth

### ISSUE THREAD

**Issue by Coop21** [mikemountain/fantasy-football-scoreboard#35]
I followed the instructions the best I could.  Ran the yahoo install both in the fantasy_football_scoreboard directory and in the pi directory.  But still getting this.  I also ran the command to create the auth folder and manually created the token.json with the auth code from the app program once I authorized it. Any help would be appreciated.  Thank you.

![image](https://user-images.githubusercontent.com/80079281/189242150-6a9518e9-6da6-46b2-bf25-9215d6a1abc4.png)

**Comment by mikemountain** [comment]
can you run `sudo pip3 install yahoo-oauth`?

**Comment by Coop21** [comment]
So that worked, but now I get this...

![image](https://user-images.githubusercontent.com/80079281/189248601-c3c73aa4-7757-44eb-b3b3-d8299c7a8949.png)

**Comment by mikemountain** [comment]
Looks like a config issue, there might be too many curly braces because it's saying there is extra data. Can you check your config.json file and make sure it's all lined up?

**Comment by Coop21** [comment]
so I think I figured out the json thing.  I get to the point where I enter in my code (I'm using Yahoo).  Then I get this...

![image](https://user-images.githubusercontent.com/80079281/189457236-d826e450-4f5a-45e2-aaf9-35f0fb09112a.png)

**Comment by mikemountain** [comment]
the auth/token.json file should look like this:

`
{
    "access_token": <very long string here>,
    "consumer_key": <consumer key string here>,
    "consumer_secret": <consumer secret string here>,
    "guid": null,
    "refresh_token": <refresh token string here>,
    "token_time": <time here>,
    "token_type": "bearer"
}
`

this should be autogenerated by the code; why did you have to manually create the token.json file?

**Comment by Coop21** [comment]
Probably because I don't know what the hell I'm doing.  

I scrapped the entire thing and started from scratch.  I think I'm past the token and json stuff.  Now it's this...

![image](https://user-images.githubusercontent.com/80079281/189461340-72fef475-8202-494f-8f99-41abe7b646c8.png)

**Comment by mikemountain** [comment]
Hahaha no worry dude! This helps me figure out what I need to clarify in my readme/install scripts. 

If there is a logos directory already, you can run `sudo chown -R $(whoami):$(whoami) logos` and it'll hopefully work after that. 

If there isn't a logos directory, then you should be able to just run `mkdir logos` and then run the program as usual. 

Can't be at my PC right now but want to make sure I can get this working for you, let me know if this works!

**Comment by Coop21** [comment]
Making progress.  Added the folder.  Now this.  Ran the chown command as well.  Maybe I need read/write privileges to the folder?

![image](https://user-images.githubusercontent.com/80079281/189461893-294c5537-902d-4170-a191-64a1f1619ffe.png)

**Comment by mikemountain** [comment]
Can you paste the output of `ls -haltr` ?

**Comment by Coop21** [comment]
![image](https://user-images.githubusercontent.com/80079281/189462315-b4a7bf16-de3c-4cef-be29-bc257656edfa.png)

**Comment by Coop21** [comment]
It's working! I was able to change the directory permissions using winscp.

**Comment by mikemountain** [comment]
Hell yeah brother, cheers! Enjoy the board, and feel free to open a new ticket if more issues happen.
