### ISSUE TITLE
Permission denied fetching logos

### ISSUE THREAD

**Issue by twholbrook** [mikemountain/fantasy-football-scoreboard#44]
Hey, think I'm pretty close to getting this working, using a Sleeper league, Got the league ID and user ID but when I run main.py I get

**_PermissionError: [Errno 13] Permission denied: '/home/pi/fantasy-football-scoreboard/logos'_**

Any ideas?

**Comment by stsmith313** [comment]
I know I'm not Mike but need to run sudo chmod 0777 logos/ from the fantasy-football-scoreboard directory.

**Comment by twholbrook** [comment]
Thanks! That worked.
