### ISSUE TITLE
Error encountered. Can't reach ESPN API

### ISSUE THREAD

**Issue by LethalDose3** [mikemountain/fantasy-football-scoreboard#48]
Displays "Error encountered. Can't reach ESPN API " after attempting to download avatars

Downloading avatar for TEAM(1-13)
/home/pi/fantasy-football-scoreboard/logos/default_avatar.png
Downloading avatar for TEAM14
Error encountered. Can't reach ESPN API

**Comment by stsmith313** [comment]
ESPN updated their API URL. You'll have update in the espn_api_parser.py file to https://lm-api.reads.fantasy.espn.com/apis/v3/games/ffl/seasons

**Comment by LethalDose3** [comment]
I updated the API URL previously, though
https://lm-api.reads.fantasy.espn.com/apis/v3/games/ffl/seasons never resolved for me, I had to change it to 
https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons which I found referenced in the reddit thread below

https://www.reddit.com/r/fantasyfootballcoding/comments/16dv9ih/espn_api_live_draft_player_pick_info/

**Comment by stsmith313** [comment]
Ah yes you're correct, sorry. I didn't realize it was a period and not a dash. I'll update that code. Is it working for you?

**Comment by mikemountain** [comment]
Thanks for this, Sam. I really need to set up a testing suite for ESPN!

@LethalDose3 feel free to reopen this issue if you have any more bugs.

**Comment by stsmith313** [comment]
All good. Sorry for the mess up guys!
